// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.zakadi.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): ZakadiPigeonError {
    return ZakadiPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is ZakadiPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class ZakadiPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class SessionStateMsg(val raw: Int) {
  IDLE(0),
  CONSENT(1),
  PERMISSION(2),
  CONNECTING(3),
  ACTIVE(4),
  ENDED(5),
  ERROR(6);

  companion object {
    fun ofRaw(raw: Int): SessionStateMsg? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AttestationKindMsg(val raw: Int) {
  PLAY_INTEGRITY(0),
  APP_ATTEST(1);

  companion object {
    fun ofRaw(raw: Int): AttestationKindMsg? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class UiActionMsg(val raw: Int) {
  REPEAT(0),
  MORE_TIME(1),
  CANCEL(2),
  REDIAL(3),
  CLOSE(4);

  companion object {
    fun ofRaw(raw: Int): UiActionMsg? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IngestCandidateMsg (
  val region: String,
  val url: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IngestCandidateMsg {
      val region = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      return IngestCandidateMsg(region, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      region,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IngestCandidateMsg
    return MessagesPigeonUtils.deepEquals(this.region, other.region) && MessagesPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.region)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.url)
    return result
  }
  override fun toString(): String {
    return "IngestCandidateMsg(region=$region, url=$url)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PromptPackRefMsg (
  val lang: String,
  val version: String,
  val url: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PromptPackRefMsg {
      val lang = pigeonVar_list[0] as String
      val version = pigeonVar_list[1] as String
      val url = pigeonVar_list[2] as String
      return PromptPackRefMsg(lang, version, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lang,
      version,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PromptPackRefMsg
    return MessagesPigeonUtils.deepEquals(this.lang, other.lang) && MessagesPigeonUtils.deepEquals(this.version, other.version) && MessagesPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lang)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.version)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.url)
    return result
  }
  override fun toString(): String {
    return "PromptPackRefMsg(lang=$lang, version=$version, url=$url)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThemeMsg (
  val colorTokens: Map<String, String>,
  val fontName: String? = null,
  val cornerRadius: Double? = null,
  val logoAssetKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThemeMsg {
      val colorTokens = pigeonVar_list[0] as Map<String, String>
      val fontName = pigeonVar_list[1] as String?
      val cornerRadius = pigeonVar_list[2] as Double?
      val logoAssetKey = pigeonVar_list[3] as String?
      return ThemeMsg(colorTokens, fontName, cornerRadius, logoAssetKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      colorTokens,
      fontName,
      cornerRadius,
      logoAssetKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ThemeMsg
    return MessagesPigeonUtils.deepEquals(this.colorTokens, other.colorTokens) && MessagesPigeonUtils.deepEquals(this.fontName, other.fontName) && MessagesPigeonUtils.deepEquals(this.cornerRadius, other.cornerRadius) && MessagesPigeonUtils.deepEquals(this.logoAssetKey, other.logoAssetKey)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.colorTokens)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fontName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cornerRadius)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.logoAssetKey)
    return result
  }
  override fun toString(): String {
    return "ThemeMsg(colorTokens=$colorTokens, fontName=$fontName, cornerRadius=$cornerRadius, logoAssetKey=$logoAssetKey)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrandMsg (
  val primary: String? = null,
  val logoUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrandMsg {
      val primary = pigeonVar_list[0] as String?
      val logoUrl = pigeonVar_list[1] as String?
      return BrandMsg(primary, logoUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primary,
      logoUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrandMsg
    return MessagesPigeonUtils.deepEquals(this.primary, other.primary) && MessagesPigeonUtils.deepEquals(this.logoUrl, other.logoUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.primary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.logoUrl)
    return result
  }
  override fun toString(): String {
    return "BrandMsg(primary=$primary, logoUrl=$logoUrl)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UiOptionsMsg (
  val character: Boolean,
  val theme: ThemeMsg,
  val brand: BrandMsg? = null,
  val consentCopy: Map<String, ConsentCopyMsg>,
  val alternatePacks: List<PromptPackRefMsg>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UiOptionsMsg {
      val character = pigeonVar_list[0] as Boolean
      val theme = pigeonVar_list[1] as ThemeMsg
      val brand = pigeonVar_list[2] as BrandMsg?
      val consentCopy = pigeonVar_list[3] as Map<String, ConsentCopyMsg>
      val alternatePacks = pigeonVar_list[4] as List<PromptPackRefMsg>
      return UiOptionsMsg(character, theme, brand, consentCopy, alternatePacks)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      character,
      theme,
      brand,
      consentCopy,
      alternatePacks,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UiOptionsMsg
    return MessagesPigeonUtils.deepEquals(this.character, other.character) && MessagesPigeonUtils.deepEquals(this.theme, other.theme) && MessagesPigeonUtils.deepEquals(this.brand, other.brand) && MessagesPigeonUtils.deepEquals(this.consentCopy, other.consentCopy) && MessagesPigeonUtils.deepEquals(this.alternatePacks, other.alternatePacks)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.character)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.theme)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.brand)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.consentCopy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alternatePacks)
    return result
  }
  override fun toString(): String {
    return "UiOptionsMsg(character=$character, theme=$theme, brand=$brand, consentCopy=$consentCopy, alternatePacks=$alternatePacks)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConsentCopyMsg (
  val title: String? = null,
  val body: String? = null,
  val recordingNotice: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConsentCopyMsg {
      val title = pigeonVar_list[0] as String?
      val body = pigeonVar_list[1] as String?
      val recordingNotice = pigeonVar_list[2] as String?
      return ConsentCopyMsg(title, body, recordingNotice)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      body,
      recordingNotice,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConsentCopyMsg
    return MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.body, other.body) && MessagesPigeonUtils.deepEquals(this.recordingNotice, other.recordingNotice)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.body)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.recordingNotice)
    return result
  }
  override fun toString(): String {
    return "ConsentCopyMsg(title=$title, body=$body, recordingNotice=$recordingNotice)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class A11yOptionsMsg (
  val screenReader: Boolean? = null,
  val captions: Boolean? = null,
  val reducedMotion: Boolean? = null,
  val extendedTime: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): A11yOptionsMsg {
      val screenReader = pigeonVar_list[0] as Boolean?
      val captions = pigeonVar_list[1] as Boolean?
      val reducedMotion = pigeonVar_list[2] as Boolean?
      val extendedTime = pigeonVar_list[3] as Boolean?
      return A11yOptionsMsg(screenReader, captions, reducedMotion, extendedTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      screenReader,
      captions,
      reducedMotion,
      extendedTime,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as A11yOptionsMsg
    return MessagesPigeonUtils.deepEquals(this.screenReader, other.screenReader) && MessagesPigeonUtils.deepEquals(this.captions, other.captions) && MessagesPigeonUtils.deepEquals(this.reducedMotion, other.reducedMotion) && MessagesPigeonUtils.deepEquals(this.extendedTime, other.extendedTime)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.screenReader)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.captions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reducedMotion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extendedTime)
    return result
  }
  override fun toString(): String {
    return "A11yOptionsMsg(screenReader=$screenReader, captions=$captions, reducedMotion=$reducedMotion, extendedTime=$extendedTime)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigMsg (
  val clientToken: String,
  val ingest: List<IngestCandidateMsg>,
  val promptPack: PromptPackRefMsg,
  val locale: String,
  val ui: UiOptionsMsg,
  val accessibility: A11yOptionsMsg,
  val hasAttestationProvider: Boolean,
  val hasTelemetrySink: Boolean,
  val priorConsentJson: String? = null,
  val apiBaseUrl: String,
  val defaultTelemetry: Boolean,
  val pinnedIntermediateSpki: List<String>,
  val sessionUiJson: String,
  val wrapperName: String,
  val wrapperVersion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigMsg {
      val clientToken = pigeonVar_list[0] as String
      val ingest = pigeonVar_list[1] as List<IngestCandidateMsg>
      val promptPack = pigeonVar_list[2] as PromptPackRefMsg
      val locale = pigeonVar_list[3] as String
      val ui = pigeonVar_list[4] as UiOptionsMsg
      val accessibility = pigeonVar_list[5] as A11yOptionsMsg
      val hasAttestationProvider = pigeonVar_list[6] as Boolean
      val hasTelemetrySink = pigeonVar_list[7] as Boolean
      val priorConsentJson = pigeonVar_list[8] as String?
      val apiBaseUrl = pigeonVar_list[9] as String
      val defaultTelemetry = pigeonVar_list[10] as Boolean
      val pinnedIntermediateSpki = pigeonVar_list[11] as List<String>
      val sessionUiJson = pigeonVar_list[12] as String
      val wrapperName = pigeonVar_list[13] as String
      val wrapperVersion = pigeonVar_list[14] as String
      return ConfigMsg(clientToken, ingest, promptPack, locale, ui, accessibility, hasAttestationProvider, hasTelemetrySink, priorConsentJson, apiBaseUrl, defaultTelemetry, pinnedIntermediateSpki, sessionUiJson, wrapperName, wrapperVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientToken,
      ingest,
      promptPack,
      locale,
      ui,
      accessibility,
      hasAttestationProvider,
      hasTelemetrySink,
      priorConsentJson,
      apiBaseUrl,
      defaultTelemetry,
      pinnedIntermediateSpki,
      sessionUiJson,
      wrapperName,
      wrapperVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConfigMsg
    return MessagesPigeonUtils.deepEquals(this.clientToken, other.clientToken) && MessagesPigeonUtils.deepEquals(this.ingest, other.ingest) && MessagesPigeonUtils.deepEquals(this.promptPack, other.promptPack) && MessagesPigeonUtils.deepEquals(this.locale, other.locale) && MessagesPigeonUtils.deepEquals(this.ui, other.ui) && MessagesPigeonUtils.deepEquals(this.accessibility, other.accessibility) && MessagesPigeonUtils.deepEquals(this.hasAttestationProvider, other.hasAttestationProvider) && MessagesPigeonUtils.deepEquals(this.hasTelemetrySink, other.hasTelemetrySink) && MessagesPigeonUtils.deepEquals(this.priorConsentJson, other.priorConsentJson) && MessagesPigeonUtils.deepEquals(this.apiBaseUrl, other.apiBaseUrl) && MessagesPigeonUtils.deepEquals(this.defaultTelemetry, other.defaultTelemetry) && MessagesPigeonUtils.deepEquals(this.pinnedIntermediateSpki, other.pinnedIntermediateSpki) && MessagesPigeonUtils.deepEquals(this.sessionUiJson, other.sessionUiJson) && MessagesPigeonUtils.deepEquals(this.wrapperName, other.wrapperName) && MessagesPigeonUtils.deepEquals(this.wrapperVersion, other.wrapperVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ingest)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.promptPack)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.locale)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ui)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessibility)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasAttestationProvider)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasTelemetrySink)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.priorConsentJson)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.apiBaseUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.defaultTelemetry)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pinnedIntermediateSpki)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionUiJson)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wrapperName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wrapperVersion)
    return result
  }
  override fun toString(): String {
    return "ConfigMsg(clientToken=$clientToken, ingest=$ingest, promptPack=$promptPack, locale=$locale, ui=$ui, accessibility=$accessibility, hasAttestationProvider=$hasAttestationProvider, hasTelemetrySink=$hasTelemetrySink, priorConsentJson=$priorConsentJson, apiBaseUrl=$apiBaseUrl, defaultTelemetry=$defaultTelemetry, pinnedIntermediateSpki=$pinnedIntermediateSpki, sessionUiJson=$sessionUiJson, wrapperName=$wrapperName, wrapperVersion=$wrapperVersion)"
  }
}

/**
 * State change plus the session facts of 8.0 item 10.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StateChangeMsg (
  val from: SessionStateMsg,
  val to: SessionStateMsg,
  val sessionId: String? = null,
  val consentRecord: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StateChangeMsg {
      val from = pigeonVar_list[0] as SessionStateMsg
      val to = pigeonVar_list[1] as SessionStateMsg
      val sessionId = pigeonVar_list[2] as String?
      val consentRecord = pigeonVar_list[3] as String?
      return StateChangeMsg(from, to, sessionId, consentRecord)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      from,
      to,
      sessionId,
      consentRecord,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StateChangeMsg
    return MessagesPigeonUtils.deepEquals(this.from, other.from) && MessagesPigeonUtils.deepEquals(this.to, other.to) && MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.consentRecord, other.consentRecord)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.from)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.to)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.consentRecord)
    return result
  }
  override fun toString(): String {
    return "StateChangeMsg(from=$from, to=$to, sessionId=$sessionId, consentRecord=$consentRecord)"
  }
}

/**
 * The flat event record of 8.0 item 10.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EventMsg (
  val type: String,
  val camera: Boolean? = null,
  val microphone: Boolean? = null,
  val region: String? = null,
  val rttMs: Long? = null,
  val phase: String? = null,
  val outcome: String? = null,
  val reason: String? = null,
  val code: String? = null,
  val message: String? = null,
  val recoverable: Boolean? = null,
  val retryAfterS: Long? = null,
  val closeCode: Long? = null,
  val sessionId: String? = null,
  val consentRecord: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EventMsg {
      val type = pigeonVar_list[0] as String
      val camera = pigeonVar_list[1] as Boolean?
      val microphone = pigeonVar_list[2] as Boolean?
      val region = pigeonVar_list[3] as String?
      val rttMs = pigeonVar_list[4] as Long?
      val phase = pigeonVar_list[5] as String?
      val outcome = pigeonVar_list[6] as String?
      val reason = pigeonVar_list[7] as String?
      val code = pigeonVar_list[8] as String?
      val message = pigeonVar_list[9] as String?
      val recoverable = pigeonVar_list[10] as Boolean?
      val retryAfterS = pigeonVar_list[11] as Long?
      val closeCode = pigeonVar_list[12] as Long?
      val sessionId = pigeonVar_list[13] as String?
      val consentRecord = pigeonVar_list[14] as String?
      return EventMsg(type, camera, microphone, region, rttMs, phase, outcome, reason, code, message, recoverable, retryAfterS, closeCode, sessionId, consentRecord)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      camera,
      microphone,
      region,
      rttMs,
      phase,
      outcome,
      reason,
      code,
      message,
      recoverable,
      retryAfterS,
      closeCode,
      sessionId,
      consentRecord,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EventMsg
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.camera, other.camera) && MessagesPigeonUtils.deepEquals(this.microphone, other.microphone) && MessagesPigeonUtils.deepEquals(this.region, other.region) && MessagesPigeonUtils.deepEquals(this.rttMs, other.rttMs) && MessagesPigeonUtils.deepEquals(this.phase, other.phase) && MessagesPigeonUtils.deepEquals(this.outcome, other.outcome) && MessagesPigeonUtils.deepEquals(this.reason, other.reason) && MessagesPigeonUtils.deepEquals(this.code, other.code) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.recoverable, other.recoverable) && MessagesPigeonUtils.deepEquals(this.retryAfterS, other.retryAfterS) && MessagesPigeonUtils.deepEquals(this.closeCode, other.closeCode) && MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.consentRecord, other.consentRecord)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.camera)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.microphone)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.region)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rttMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.phase)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outcome)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reason)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.recoverable)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.retryAfterS)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.closeCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.consentRecord)
    return result
  }
  override fun toString(): String {
    return "EventMsg(type=$type, camera=$camera, microphone=$microphone, region=$region, rttMs=$rttMs, phase=$phase, outcome=$outcome, reason=$reason, code=$code, message=$message, recoverable=$recoverable, retryAfterS=$retryAfterS, closeCode=$closeCode, sessionId=$sessionId, consentRecord=$consentRecord)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttestationRequestMsg (
  val nonce: ByteArray,
  val sessionId: String,
  val requestHash: ByteArray,
  val requestHashHex: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttestationRequestMsg {
      val nonce = pigeonVar_list[0] as ByteArray
      val sessionId = pigeonVar_list[1] as String
      val requestHash = pigeonVar_list[2] as ByteArray
      val requestHashHex = pigeonVar_list[3] as String
      return AttestationRequestMsg(nonce, sessionId, requestHash, requestHashHex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nonce,
      sessionId,
      requestHash,
      requestHashHex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttestationRequestMsg
    return MessagesPigeonUtils.deepEquals(this.nonce, other.nonce) && MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.requestHash, other.requestHash) && MessagesPigeonUtils.deepEquals(this.requestHashHex, other.requestHashHex)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nonce)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestHash)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestHashHex)
    return result
  }
  override fun toString(): String {
    return "AttestationRequestMsg(nonce=${nonce.contentToString()}, sessionId=$sessionId, requestHash=${requestHash.contentToString()}, requestHashHex=$requestHashHex)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttestationTokenMsg (
  val kind: AttestationKindMsg,
  val token: String? = null,
  val appAttestKeyId: String? = null,
  val appAttestAttestation: ByteArray? = null,
  val appAttestAssertion: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttestationTokenMsg {
      val kind = pigeonVar_list[0] as AttestationKindMsg
      val token = pigeonVar_list[1] as String?
      val appAttestKeyId = pigeonVar_list[2] as String?
      val appAttestAttestation = pigeonVar_list[3] as ByteArray?
      val appAttestAssertion = pigeonVar_list[4] as ByteArray?
      return AttestationTokenMsg(kind, token, appAttestKeyId, appAttestAttestation, appAttestAssertion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      token,
      appAttestKeyId,
      appAttestAttestation,
      appAttestAssertion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttestationTokenMsg
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.token, other.token) && MessagesPigeonUtils.deepEquals(this.appAttestKeyId, other.appAttestKeyId) && MessagesPigeonUtils.deepEquals(this.appAttestAttestation, other.appAttestAttestation) && MessagesPigeonUtils.deepEquals(this.appAttestAssertion, other.appAttestAssertion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.token)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appAttestKeyId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appAttestAttestation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appAttestAssertion)
    return result
  }
  override fun toString(): String {
    return "AttestationTokenMsg(kind=$kind, token=$token, appAttestKeyId=$appAttestKeyId, appAttestAttestation=${appAttestAttestation?.contentToString()}, appAttestAssertion=${appAttestAssertion?.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TelemetryMsg (
  val name: String,
  val sessionId: String? = null,
  val tMs: Long,
  val fields: Map<String, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TelemetryMsg {
      val name = pigeonVar_list[0] as String
      val sessionId = pigeonVar_list[1] as String?
      val tMs = pigeonVar_list[2] as Long
      val fields = pigeonVar_list[3] as Map<String, Any?>
      return TelemetryMsg(name, sessionId, tMs, fields)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      sessionId,
      tMs,
      fields,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TelemetryMsg
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.tMs, other.tMs) && MessagesPigeonUtils.deepEquals(this.fields, other.fields)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fields)
    return result
  }
  override fun toString(): String {
    return "TelemetryMsg(name=$name, sessionId=$sessionId, tMs=$tMs, fields=$fields)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SessionStateMsg.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AttestationKindMsg.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          UiActionMsg.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IngestCandidateMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PromptPackRefMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThemeMsg.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrandMsg.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UiOptionsMsg.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConsentCopyMsg.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          A11yOptionsMsg.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigMsg.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StateChangeMsg.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EventMsg.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttestationRequestMsg.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttestationTokenMsg.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TelemetryMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SessionStateMsg -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AttestationKindMsg -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is UiActionMsg -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is IngestCandidateMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PromptPackRefMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ThemeMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BrandMsg -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is UiOptionsMsg -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ConsentCopyMsg -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is A11yOptionsMsg -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ConfigMsg -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is StateChangeMsg -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is EventMsg -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is AttestationRequestMsg -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is AttestationTokenMsg -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is TelemetryMsg -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ZakadiHostApi {
  /** Closes sessions created by an earlier Dart isolate (hot restart); records this isolate's epoch. */
  fun initialize(isolateEpoch: String)
  /** Constructs the native ZakadiSession; returns its handle. Errors: unsupported_device, usage_error. */
  fun create(config: ConfigMsg): String
  /** Completes at `active`; otherwise throws ZakadiPigeonError(code = 5.11 wire code). */
  suspend fun start(handle: String)
  fun cancel(handle: String, reason: String?)
  fun perform(handle: String, action: UiActionMsg)
  fun dispose(handle: String)
  /** Reply to ZakadiFlutterApi.onAttestationRequested; null = no attestation. */
  fun provideAttestation(handle: String, requestId: String, token: AttestationTokenMsg?)

  companion object {
    /** The codec used by ZakadiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ZakadiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ZakadiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isolateEpochArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.initialize(isolateEpochArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ConfigMsg
            val wrapped: List<Any?> = try {
              listOf(api.create(configArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.start(handleArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            val reasonArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.cancel(handleArg, reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.perform$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            val actionArg = args[1] as UiActionMsg
            val wrapped: List<Any?> = try {
              api.perform(handleArg, actionArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.dispose(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.provideAttestation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            val requestIdArg = args[1] as String
            val tokenArg = args[2] as AttestationTokenMsg?
            val wrapped: List<Any?> = try {
              api.provideAttestation(handleArg, requestIdArg, tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ZakadiFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ZakadiFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun onState(handleArg: String, changeArg: StateChangeMsg)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onState$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(handleArg, changeArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(ZakadiPigeonError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onEvent(handleArg: String, eventArg: EventMsg)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(handleArg, eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(ZakadiPigeonError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onAttestationRequested(handleArg: String, requestIdArg: String, requestArg: AttestationRequestMsg)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onAttestationRequested$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(handleArg, requestIdArg, requestArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(ZakadiPigeonError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onTelemetry(handleArg: String, eventArg: TelemetryMsg)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onTelemetry$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(handleArg, eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(ZakadiPigeonError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
