// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class ZakadiPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "ZakadiPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? ZakadiPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> ZakadiPigeonError {
  return ZakadiPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum SessionStateMsg: Int, CaseIterable {
  case idle = 0
  case consent = 1
  case permission = 2
  case connecting = 3
  case active = 4
  case ended = 5
  case error = 6
}

enum AttestationKindMsg: Int, CaseIterable {
  case playIntegrity = 0
  case appAttest = 1
}

enum UiActionMsg: Int, CaseIterable {
  case `repeat` = 0
  case moreTime = 1
  case cancel = 2
  case redial = 3
  case close = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct IngestCandidateMsg: Hashable, CustomStringConvertible {
  var region: String
  var url: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IngestCandidateMsg? {
    let region = pigeonVar_list[0] as! String
    let url = pigeonVar_list[1] as! String

    return IngestCandidateMsg(
      region: region,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      region,
      url,
    ]
  }
  static func == (lhs: IngestCandidateMsg, rhs: IngestCandidateMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.region, rhs.region) && MessagesPigeonInternal.deepEquals(lhs.url, rhs.url)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IngestCandidateMsg")
    MessagesPigeonInternal.deepHash(value: region, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: url, hasher: &hasher)
  }

  public var description: String {
    return "IngestCandidateMsg(region: \(String(describing: region)), url: \(String(describing: url)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PromptPackRefMsg: Hashable, CustomStringConvertible {
  var lang: String
  var version: String
  var url: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PromptPackRefMsg? {
    let lang = pigeonVar_list[0] as! String
    let version = pigeonVar_list[1] as! String
    let url = pigeonVar_list[2] as! String

    return PromptPackRefMsg(
      lang: lang,
      version: version,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      lang,
      version,
      url,
    ]
  }
  static func == (lhs: PromptPackRefMsg, rhs: PromptPackRefMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.lang, rhs.lang) && MessagesPigeonInternal.deepEquals(lhs.version, rhs.version) && MessagesPigeonInternal.deepEquals(lhs.url, rhs.url)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PromptPackRefMsg")
    MessagesPigeonInternal.deepHash(value: lang, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: version, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: url, hasher: &hasher)
  }

  public var description: String {
    return "PromptPackRefMsg(lang: \(String(describing: lang)), version: \(String(describing: version)), url: \(String(describing: url)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThemeMsg: Hashable, CustomStringConvertible {
  var colorTokens: [String: String]
  var fontName: String? = nil
  var cornerRadius: Double? = nil
  var logoAssetKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThemeMsg? {
    let colorTokens = pigeonVar_list[0] as! [String: String]
    let fontName: String? = nilOrValue(pigeonVar_list[1])
    let cornerRadius: Double? = nilOrValue(pigeonVar_list[2])
    let logoAssetKey: String? = nilOrValue(pigeonVar_list[3])

    return ThemeMsg(
      colorTokens: colorTokens,
      fontName: fontName,
      cornerRadius: cornerRadius,
      logoAssetKey: logoAssetKey
    )
  }
  func toList() -> [Any?] {
    return [
      colorTokens,
      fontName,
      cornerRadius,
      logoAssetKey,
    ]
  }
  static func == (lhs: ThemeMsg, rhs: ThemeMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.colorTokens, rhs.colorTokens) && MessagesPigeonInternal.deepEquals(lhs.fontName, rhs.fontName) && MessagesPigeonInternal.deepEquals(lhs.cornerRadius, rhs.cornerRadius) && MessagesPigeonInternal.deepEquals(lhs.logoAssetKey, rhs.logoAssetKey)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThemeMsg")
    MessagesPigeonInternal.deepHash(value: colorTokens, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fontName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cornerRadius, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: logoAssetKey, hasher: &hasher)
  }

  public var description: String {
    return "ThemeMsg(colorTokens: \(String(describing: colorTokens)), fontName: \(String(describing: fontName)), cornerRadius: \(String(describing: cornerRadius)), logoAssetKey: \(String(describing: logoAssetKey)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BrandMsg: Hashable, CustomStringConvertible {
  var primary: String? = nil
  var logoUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BrandMsg? {
    let primary: String? = nilOrValue(pigeonVar_list[0])
    let logoUrl: String? = nilOrValue(pigeonVar_list[1])

    return BrandMsg(
      primary: primary,
      logoUrl: logoUrl
    )
  }
  func toList() -> [Any?] {
    return [
      primary,
      logoUrl,
    ]
  }
  static func == (lhs: BrandMsg, rhs: BrandMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.primary, rhs.primary) && MessagesPigeonInternal.deepEquals(lhs.logoUrl, rhs.logoUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BrandMsg")
    MessagesPigeonInternal.deepHash(value: primary, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: logoUrl, hasher: &hasher)
  }

  public var description: String {
    return "BrandMsg(primary: \(String(describing: primary)), logoUrl: \(String(describing: logoUrl)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UiOptionsMsg: Hashable, CustomStringConvertible {
  var character: Bool
  var theme: ThemeMsg
  var brand: BrandMsg? = nil
  var consentCopy: [String: ConsentCopyMsg]
  var alternatePacks: [PromptPackRefMsg]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UiOptionsMsg? {
    let character = pigeonVar_list[0] as! Bool
    let theme = pigeonVar_list[1] as! ThemeMsg
    let brand: BrandMsg? = nilOrValue(pigeonVar_list[2])
    let consentCopy = pigeonVar_list[3] as! [String: ConsentCopyMsg]
    let alternatePacks = pigeonVar_list[4] as! [PromptPackRefMsg]

    return UiOptionsMsg(
      character: character,
      theme: theme,
      brand: brand,
      consentCopy: consentCopy,
      alternatePacks: alternatePacks
    )
  }
  func toList() -> [Any?] {
    return [
      character,
      theme,
      brand,
      consentCopy,
      alternatePacks,
    ]
  }
  static func == (lhs: UiOptionsMsg, rhs: UiOptionsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.character, rhs.character) && MessagesPigeonInternal.deepEquals(lhs.theme, rhs.theme) && MessagesPigeonInternal.deepEquals(lhs.brand, rhs.brand) && MessagesPigeonInternal.deepEquals(lhs.consentCopy, rhs.consentCopy) && MessagesPigeonInternal.deepEquals(lhs.alternatePacks, rhs.alternatePacks)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UiOptionsMsg")
    MessagesPigeonInternal.deepHash(value: character, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: theme, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: brand, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: consentCopy, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alternatePacks, hasher: &hasher)
  }

  public var description: String {
    return "UiOptionsMsg(character: \(String(describing: character)), theme: \(String(describing: theme)), brand: \(String(describing: brand)), consentCopy: \(String(describing: consentCopy)), alternatePacks: \(String(describing: alternatePacks)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConsentCopyMsg: Hashable, CustomStringConvertible {
  var title: String? = nil
  var body: String? = nil
  var recordingNotice: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConsentCopyMsg? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let body: String? = nilOrValue(pigeonVar_list[1])
    let recordingNotice: String? = nilOrValue(pigeonVar_list[2])

    return ConsentCopyMsg(
      title: title,
      body: body,
      recordingNotice: recordingNotice
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      body,
      recordingNotice,
    ]
  }
  static func == (lhs: ConsentCopyMsg, rhs: ConsentCopyMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.body, rhs.body) && MessagesPigeonInternal.deepEquals(lhs.recordingNotice, rhs.recordingNotice)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConsentCopyMsg")
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: body, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: recordingNotice, hasher: &hasher)
  }

  public var description: String {
    return "ConsentCopyMsg(title: \(String(describing: title)), body: \(String(describing: body)), recordingNotice: \(String(describing: recordingNotice)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct A11yOptionsMsg: Hashable, CustomStringConvertible {
  var screenReader: Bool? = nil
  var captions: Bool? = nil
  var reducedMotion: Bool? = nil
  var extendedTime: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> A11yOptionsMsg? {
    let screenReader: Bool? = nilOrValue(pigeonVar_list[0])
    let captions: Bool? = nilOrValue(pigeonVar_list[1])
    let reducedMotion: Bool? = nilOrValue(pigeonVar_list[2])
    let extendedTime: Bool? = nilOrValue(pigeonVar_list[3])

    return A11yOptionsMsg(
      screenReader: screenReader,
      captions: captions,
      reducedMotion: reducedMotion,
      extendedTime: extendedTime
    )
  }
  func toList() -> [Any?] {
    return [
      screenReader,
      captions,
      reducedMotion,
      extendedTime,
    ]
  }
  static func == (lhs: A11yOptionsMsg, rhs: A11yOptionsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.screenReader, rhs.screenReader) && MessagesPigeonInternal.deepEquals(lhs.captions, rhs.captions) && MessagesPigeonInternal.deepEquals(lhs.reducedMotion, rhs.reducedMotion) && MessagesPigeonInternal.deepEquals(lhs.extendedTime, rhs.extendedTime)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("A11yOptionsMsg")
    MessagesPigeonInternal.deepHash(value: screenReader, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: captions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reducedMotion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extendedTime, hasher: &hasher)
  }

  public var description: String {
    return "A11yOptionsMsg(screenReader: \(String(describing: screenReader)), captions: \(String(describing: captions)), reducedMotion: \(String(describing: reducedMotion)), extendedTime: \(String(describing: extendedTime)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfigMsg: Hashable, CustomStringConvertible {
  var clientToken: String
  var ingest: [IngestCandidateMsg]
  var promptPack: PromptPackRefMsg
  var locale: String
  var ui: UiOptionsMsg
  var accessibility: A11yOptionsMsg
  var hasAttestationProvider: Bool
  var hasTelemetrySink: Bool
  var priorConsentJson: String? = nil
  var apiBaseUrl: String
  var defaultTelemetry: Bool
  var pinnedIntermediateSpki: [String]
  var sessionUiJson: String
  var wrapperName: String
  var wrapperVersion: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigMsg? {
    let clientToken = pigeonVar_list[0] as! String
    let ingest = pigeonVar_list[1] as! [IngestCandidateMsg]
    let promptPack = pigeonVar_list[2] as! PromptPackRefMsg
    let locale = pigeonVar_list[3] as! String
    let ui = pigeonVar_list[4] as! UiOptionsMsg
    let accessibility = pigeonVar_list[5] as! A11yOptionsMsg
    let hasAttestationProvider = pigeonVar_list[6] as! Bool
    let hasTelemetrySink = pigeonVar_list[7] as! Bool
    let priorConsentJson: String? = nilOrValue(pigeonVar_list[8])
    let apiBaseUrl = pigeonVar_list[9] as! String
    let defaultTelemetry = pigeonVar_list[10] as! Bool
    let pinnedIntermediateSpki = pigeonVar_list[11] as! [String]
    let sessionUiJson = pigeonVar_list[12] as! String
    let wrapperName = pigeonVar_list[13] as! String
    let wrapperVersion = pigeonVar_list[14] as! String

    return ConfigMsg(
      clientToken: clientToken,
      ingest: ingest,
      promptPack: promptPack,
      locale: locale,
      ui: ui,
      accessibility: accessibility,
      hasAttestationProvider: hasAttestationProvider,
      hasTelemetrySink: hasTelemetrySink,
      priorConsentJson: priorConsentJson,
      apiBaseUrl: apiBaseUrl,
      defaultTelemetry: defaultTelemetry,
      pinnedIntermediateSpki: pinnedIntermediateSpki,
      sessionUiJson: sessionUiJson,
      wrapperName: wrapperName,
      wrapperVersion: wrapperVersion
    )
  }
  func toList() -> [Any?] {
    return [
      clientToken,
      ingest,
      promptPack,
      locale,
      ui,
      accessibility,
      hasAttestationProvider,
      hasTelemetrySink,
      priorConsentJson,
      apiBaseUrl,
      defaultTelemetry,
      pinnedIntermediateSpki,
      sessionUiJson,
      wrapperName,
      wrapperVersion,
    ]
  }
  static func == (lhs: ConfigMsg, rhs: ConfigMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.clientToken, rhs.clientToken) && MessagesPigeonInternal.deepEquals(lhs.ingest, rhs.ingest) && MessagesPigeonInternal.deepEquals(lhs.promptPack, rhs.promptPack) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.ui, rhs.ui) && MessagesPigeonInternal.deepEquals(lhs.accessibility, rhs.accessibility) && MessagesPigeonInternal.deepEquals(lhs.hasAttestationProvider, rhs.hasAttestationProvider) && MessagesPigeonInternal.deepEquals(lhs.hasTelemetrySink, rhs.hasTelemetrySink) && MessagesPigeonInternal.deepEquals(lhs.priorConsentJson, rhs.priorConsentJson) && MessagesPigeonInternal.deepEquals(lhs.apiBaseUrl, rhs.apiBaseUrl) && MessagesPigeonInternal.deepEquals(lhs.defaultTelemetry, rhs.defaultTelemetry) && MessagesPigeonInternal.deepEquals(lhs.pinnedIntermediateSpki, rhs.pinnedIntermediateSpki) && MessagesPigeonInternal.deepEquals(lhs.sessionUiJson, rhs.sessionUiJson) && MessagesPigeonInternal.deepEquals(lhs.wrapperName, rhs.wrapperName) && MessagesPigeonInternal.deepEquals(lhs.wrapperVersion, rhs.wrapperVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConfigMsg")
    MessagesPigeonInternal.deepHash(value: clientToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ingest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: promptPack, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ui, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: accessibility, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasAttestationProvider, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasTelemetrySink, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: priorConsentJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: apiBaseUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: defaultTelemetry, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pinnedIntermediateSpki, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionUiJson, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wrapperName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wrapperVersion, hasher: &hasher)
  }

  public var description: String {
    return "ConfigMsg(clientToken: \(String(describing: clientToken)), ingest: \(String(describing: ingest)), promptPack: \(String(describing: promptPack)), locale: \(String(describing: locale)), ui: \(String(describing: ui)), accessibility: \(String(describing: accessibility)), hasAttestationProvider: \(String(describing: hasAttestationProvider)), hasTelemetrySink: \(String(describing: hasTelemetrySink)), priorConsentJson: \(String(describing: priorConsentJson)), apiBaseUrl: \(String(describing: apiBaseUrl)), defaultTelemetry: \(String(describing: defaultTelemetry)), pinnedIntermediateSpki: \(String(describing: pinnedIntermediateSpki)), sessionUiJson: \(String(describing: sessionUiJson)), wrapperName: \(String(describing: wrapperName)), wrapperVersion: \(String(describing: wrapperVersion)))"
  }
}

/// State change plus the session facts of 8.0 item 10.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StateChangeMsg: Hashable, CustomStringConvertible {
  var from: SessionStateMsg
  var to: SessionStateMsg
  var sessionId: String? = nil
  var consentRecord: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StateChangeMsg? {
    let from = pigeonVar_list[0] as! SessionStateMsg
    let to = pigeonVar_list[1] as! SessionStateMsg
    let sessionId: String? = nilOrValue(pigeonVar_list[2])
    let consentRecord: String? = nilOrValue(pigeonVar_list[3])

    return StateChangeMsg(
      from: from,
      to: to,
      sessionId: sessionId,
      consentRecord: consentRecord
    )
  }
  func toList() -> [Any?] {
    return [
      from,
      to,
      sessionId,
      consentRecord,
    ]
  }
  static func == (lhs: StateChangeMsg, rhs: StateChangeMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.from, rhs.from) && MessagesPigeonInternal.deepEquals(lhs.to, rhs.to) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.consentRecord, rhs.consentRecord)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StateChangeMsg")
    MessagesPigeonInternal.deepHash(value: from, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: to, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: consentRecord, hasher: &hasher)
  }

  public var description: String {
    return "StateChangeMsg(from: \(String(describing: from)), to: \(String(describing: to)), sessionId: \(String(describing: sessionId)), consentRecord: \(String(describing: consentRecord)))"
  }
}

/// The flat event record of 8.0 item 10.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EventMsg: Hashable, CustomStringConvertible {
  var type: String
  var camera: Bool? = nil
  var microphone: Bool? = nil
  var region: String? = nil
  var rttMs: Int64? = nil
  var phase: String? = nil
  var outcome: String? = nil
  var reason: String? = nil
  var code: String? = nil
  var message: String? = nil
  var recoverable: Bool? = nil
  var retryAfterS: Int64? = nil
  var closeCode: Int64? = nil
  var sessionId: String? = nil
  var consentRecord: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EventMsg? {
    let type = pigeonVar_list[0] as! String
    let camera: Bool? = nilOrValue(pigeonVar_list[1])
    let microphone: Bool? = nilOrValue(pigeonVar_list[2])
    let region: String? = nilOrValue(pigeonVar_list[3])
    let rttMs: Int64? = nilOrValue(pigeonVar_list[4])
    let phase: String? = nilOrValue(pigeonVar_list[5])
    let outcome: String? = nilOrValue(pigeonVar_list[6])
    let reason: String? = nilOrValue(pigeonVar_list[7])
    let code: String? = nilOrValue(pigeonVar_list[8])
    let message: String? = nilOrValue(pigeonVar_list[9])
    let recoverable: Bool? = nilOrValue(pigeonVar_list[10])
    let retryAfterS: Int64? = nilOrValue(pigeonVar_list[11])
    let closeCode: Int64? = nilOrValue(pigeonVar_list[12])
    let sessionId: String? = nilOrValue(pigeonVar_list[13])
    let consentRecord: String? = nilOrValue(pigeonVar_list[14])

    return EventMsg(
      type: type,
      camera: camera,
      microphone: microphone,
      region: region,
      rttMs: rttMs,
      phase: phase,
      outcome: outcome,
      reason: reason,
      code: code,
      message: message,
      recoverable: recoverable,
      retryAfterS: retryAfterS,
      closeCode: closeCode,
      sessionId: sessionId,
      consentRecord: consentRecord
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      camera,
      microphone,
      region,
      rttMs,
      phase,
      outcome,
      reason,
      code,
      message,
      recoverable,
      retryAfterS,
      closeCode,
      sessionId,
      consentRecord,
    ]
  }
  static func == (lhs: EventMsg, rhs: EventMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.camera, rhs.camera) && MessagesPigeonInternal.deepEquals(lhs.microphone, rhs.microphone) && MessagesPigeonInternal.deepEquals(lhs.region, rhs.region) && MessagesPigeonInternal.deepEquals(lhs.rttMs, rhs.rttMs) && MessagesPigeonInternal.deepEquals(lhs.phase, rhs.phase) && MessagesPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && MessagesPigeonInternal.deepEquals(lhs.reason, rhs.reason) && MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.recoverable, rhs.recoverable) && MessagesPigeonInternal.deepEquals(lhs.retryAfterS, rhs.retryAfterS) && MessagesPigeonInternal.deepEquals(lhs.closeCode, rhs.closeCode) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.consentRecord, rhs.consentRecord)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EventMsg")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: camera, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: microphone, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: region, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rttMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: phase, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reason, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: recoverable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: retryAfterS, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: closeCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: consentRecord, hasher: &hasher)
  }

  public var description: String {
    return "EventMsg(type: \(String(describing: type)), camera: \(String(describing: camera)), microphone: \(String(describing: microphone)), region: \(String(describing: region)), rttMs: \(String(describing: rttMs)), phase: \(String(describing: phase)), outcome: \(String(describing: outcome)), reason: \(String(describing: reason)), code: \(String(describing: code)), message: \(String(describing: message)), recoverable: \(String(describing: recoverable)), retryAfterS: \(String(describing: retryAfterS)), closeCode: \(String(describing: closeCode)), sessionId: \(String(describing: sessionId)), consentRecord: \(String(describing: consentRecord)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttestationRequestMsg: Hashable, CustomStringConvertible {
  var nonce: FlutterStandardTypedData
  var sessionId: String
  var requestHash: FlutterStandardTypedData
  var requestHashHex: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttestationRequestMsg? {
    let nonce = pigeonVar_list[0] as! FlutterStandardTypedData
    let sessionId = pigeonVar_list[1] as! String
    let requestHash = pigeonVar_list[2] as! FlutterStandardTypedData
    let requestHashHex = pigeonVar_list[3] as! String

    return AttestationRequestMsg(
      nonce: nonce,
      sessionId: sessionId,
      requestHash: requestHash,
      requestHashHex: requestHashHex
    )
  }
  func toList() -> [Any?] {
    return [
      nonce,
      sessionId,
      requestHash,
      requestHashHex,
    ]
  }
  static func == (lhs: AttestationRequestMsg, rhs: AttestationRequestMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.nonce, rhs.nonce) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.requestHash, rhs.requestHash) && MessagesPigeonInternal.deepEquals(lhs.requestHashHex, rhs.requestHashHex)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttestationRequestMsg")
    MessagesPigeonInternal.deepHash(value: nonce, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestHash, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestHashHex, hasher: &hasher)
  }

  public var description: String {
    return "AttestationRequestMsg(nonce: \(String(describing: nonce)), sessionId: \(String(describing: sessionId)), requestHash: \(String(describing: requestHash)), requestHashHex: \(String(describing: requestHashHex)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttestationTokenMsg: Hashable, CustomStringConvertible {
  var kind: AttestationKindMsg
  var token: String? = nil
  var appAttestKeyId: String? = nil
  var appAttestAttestation: FlutterStandardTypedData? = nil
  var appAttestAssertion: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttestationTokenMsg? {
    let kind = pigeonVar_list[0] as! AttestationKindMsg
    let token: String? = nilOrValue(pigeonVar_list[1])
    let appAttestKeyId: String? = nilOrValue(pigeonVar_list[2])
    let appAttestAttestation: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])
    let appAttestAssertion: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])

    return AttestationTokenMsg(
      kind: kind,
      token: token,
      appAttestKeyId: appAttestKeyId,
      appAttestAttestation: appAttestAttestation,
      appAttestAssertion: appAttestAssertion
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      token,
      appAttestKeyId,
      appAttestAttestation,
      appAttestAssertion,
    ]
  }
  static func == (lhs: AttestationTokenMsg, rhs: AttestationTokenMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.token, rhs.token) && MessagesPigeonInternal.deepEquals(lhs.appAttestKeyId, rhs.appAttestKeyId) && MessagesPigeonInternal.deepEquals(lhs.appAttestAttestation, rhs.appAttestAttestation) && MessagesPigeonInternal.deepEquals(lhs.appAttestAssertion, rhs.appAttestAssertion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttestationTokenMsg")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: token, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appAttestKeyId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appAttestAttestation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appAttestAssertion, hasher: &hasher)
  }

  public var description: String {
    return "AttestationTokenMsg(kind: \(String(describing: kind)), token: \(String(describing: token)), appAttestKeyId: \(String(describing: appAttestKeyId)), appAttestAttestation: \(String(describing: appAttestAttestation)), appAttestAssertion: \(String(describing: appAttestAssertion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TelemetryMsg: Hashable, CustomStringConvertible {
  var name: String
  var sessionId: String? = nil
  var tMs: Int64
  var fields: [String: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TelemetryMsg? {
    let name = pigeonVar_list[0] as! String
    let sessionId: String? = nilOrValue(pigeonVar_list[1])
    let tMs = pigeonVar_list[2] as! Int64
    let fields = pigeonVar_list[3] as! [String: Any?]

    return TelemetryMsg(
      name: name,
      sessionId: sessionId,
      tMs: tMs,
      fields: fields
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      sessionId,
      tMs,
      fields,
    ]
  }
  static func == (lhs: TelemetryMsg, rhs: TelemetryMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.tMs, rhs.tMs) && MessagesPigeonInternal.deepEquals(lhs.fields, rhs.fields)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TelemetryMsg")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fields, hasher: &hasher)
  }

  public var description: String {
    return "TelemetryMsg(name: \(String(describing: name)), sessionId: \(String(describing: sessionId)), tMs: \(String(describing: tMs)), fields: \(String(describing: fields)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SessionStateMsg(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AttestationKindMsg(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UiActionMsg(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return IngestCandidateMsg.fromList(self.readValue() as! [Any?])
    case 133:
      return PromptPackRefMsg.fromList(self.readValue() as! [Any?])
    case 134:
      return ThemeMsg.fromList(self.readValue() as! [Any?])
    case 135:
      return BrandMsg.fromList(self.readValue() as! [Any?])
    case 136:
      return UiOptionsMsg.fromList(self.readValue() as! [Any?])
    case 137:
      return ConsentCopyMsg.fromList(self.readValue() as! [Any?])
    case 138:
      return A11yOptionsMsg.fromList(self.readValue() as! [Any?])
    case 139:
      return ConfigMsg.fromList(self.readValue() as! [Any?])
    case 140:
      return StateChangeMsg.fromList(self.readValue() as! [Any?])
    case 141:
      return EventMsg.fromList(self.readValue() as! [Any?])
    case 142:
      return AttestationRequestMsg.fromList(self.readValue() as! [Any?])
    case 143:
      return AttestationTokenMsg.fromList(self.readValue() as! [Any?])
    case 144:
      return TelemetryMsg.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SessionStateMsg {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AttestationKindMsg {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? UiActionMsg {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? IngestCandidateMsg {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PromptPackRefMsg {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ThemeMsg {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BrandMsg {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? UiOptionsMsg {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ConsentCopyMsg {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? A11yOptionsMsg {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ConfigMsg {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? StateChangeMsg {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? EventMsg {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? AttestationRequestMsg {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? AttestationTokenMsg {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? TelemetryMsg {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ZakadiHostApi {
  /// Closes sessions created by an earlier Dart isolate (hot restart); records this isolate's epoch.
  func initialize(isolateEpoch: String) throws
  /// Constructs the native ZakadiSession; returns its handle. Errors: unsupported_device, usage_error.
  func create(config: ConfigMsg) throws -> String
  /// Completes at `active`; otherwise throws ZakadiPigeonError(code = 5.11 wire code).
  func start(handle: String) async throws
  func cancel(handle: String, reason: String?) throws
  func perform(handle: String, action: UiActionMsg) throws
  func dispose(handle: String) throws
  /// Reply to ZakadiFlutterApi.onAttestationRequested; null = no attestation.
  func provideAttestation(handle: String, requestId: String, token: AttestationTokenMsg?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ZakadiHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ZakadiHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ZakadiHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Closes sessions created by an earlier Dart isolate (hot restart); records this isolate's epoch.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isolateEpochArg = args[0] as! String
        do {
          try api.initialize(isolateEpoch: isolateEpochArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Constructs the native ZakadiSession; returns its handle. Errors: unsupported_device, usage_error.
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ConfigMsg
        do {
          let result = try api.create(config: configArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    /// Completes at `active`; otherwise throws ZakadiPigeonError(code = 5.11 wire code).
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.start(handle: handleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        let reasonArg: String? = nilOrValue(args[1])
        do {
          try api.cancel(handle: handleArg, reason: reasonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    let performChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.perform\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      performChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        let actionArg = args[1] as! UiActionMsg
        do {
          try api.perform(handle: handleArg, action: actionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      performChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        do {
          try api.dispose(handle: handleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    /// Reply to ZakadiFlutterApi.onAttestationRequested; null = no attestation.
    let provideAttestationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiHostApi.provideAttestation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      provideAttestationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        let requestIdArg = args[1] as! String
        let tokenArg: AttestationTokenMsg? = nilOrValue(args[2])
        do {
          try api.provideAttestation(handle: handleArg, requestId: requestIdArg, token: tokenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      provideAttestationChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ZakadiFlutterApiProtocol {
  @MainActor func onState(handle handleArg: String, change changeArg: StateChangeMsg) async throws
  @MainActor func onEvent(handle handleArg: String, event eventArg: EventMsg) async throws
  @MainActor func onAttestationRequested(handle handleArg: String, requestId requestIdArg: String, request requestArg: AttestationRequestMsg) async throws
  @MainActor func onTelemetry(handle handleArg: String, event eventArg: TelemetryMsg) async throws
}
class ZakadiFlutterApi: ZakadiFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  @MainActor func onState(handle handleArg: String, change changeArg: StateChangeMsg) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiFlutterApi.onState\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([handleArg, changeArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: ZakadiPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onEvent(handle handleArg: String, event eventArg: EventMsg) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiFlutterApi.onEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([handleArg, eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: ZakadiPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onAttestationRequested(handle handleArg: String, requestId requestIdArg: String, request requestArg: AttestationRequestMsg) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiFlutterApi.onAttestationRequested\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([handleArg, requestIdArg, requestArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: ZakadiPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onTelemetry(handle handleArg: String, event eventArg: TelemetryMsg) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.zakadi_sdk_ios.ZakadiFlutterApi.onTelemetry\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([handleArg, eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: ZakadiPigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
