// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers, omit_obvious_local_variable_types
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:zakadi_sdk_android/src/messages.g.dart';

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SessionStateMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AttestationKindMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is UiActionMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is IngestCandidateMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PromptPackRefMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ThemeMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is BrandMsg) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is UiOptionsMsg) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ConsentCopyMsg) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is A11yOptionsMsg) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is ConfigMsg) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is StateChangeMsg) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is EventMsg) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is AttestationRequestMsg) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is AttestationTokenMsg) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is TelemetryMsg) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SessionStateMsg.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AttestationKindMsg.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : UiActionMsg.values[value];
      case 132:
        return IngestCandidateMsg.decode(readValue(buffer)!);
      case 133:
        return PromptPackRefMsg.decode(readValue(buffer)!);
      case 134:
        return ThemeMsg.decode(readValue(buffer)!);
      case 135:
        return BrandMsg.decode(readValue(buffer)!);
      case 136:
        return UiOptionsMsg.decode(readValue(buffer)!);
      case 137:
        return ConsentCopyMsg.decode(readValue(buffer)!);
      case 138:
        return A11yOptionsMsg.decode(readValue(buffer)!);
      case 139:
        return ConfigMsg.decode(readValue(buffer)!);
      case 140:
        return StateChangeMsg.decode(readValue(buffer)!);
      case 141:
        return EventMsg.decode(readValue(buffer)!);
      case 142:
        return AttestationRequestMsg.decode(readValue(buffer)!);
      case 143:
        return AttestationTokenMsg.decode(readValue(buffer)!);
      case 144:
        return TelemetryMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class TestZakadiHostApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding =>
      TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Closes sessions created by an earlier Dart isolate (hot restart); records this isolate's epoch.
  void initialize(String isolateEpoch);

  /// Constructs the native ZakadiSession; returns its handle. Errors: unsupported_device, usage_error.
  String create(ConfigMsg config);

  /// Completes at `active`; otherwise throws ZakadiPigeonError(code = 5.11 wire code).
  Future<void> start(String handle);

  void cancel(String handle, String? reason);

  void perform(String handle, UiActionMsg action);

  void dispose(String handle);

  /// Reply to ZakadiFlutterApi.onAttestationRequested; null = no attestation.
  void provideAttestation(
    String handle,
    String requestId,
    AttestationTokenMsg? token,
  );

  static void setUp(
    TestZakadiHostApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.initialize$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_isolateEpoch = args[0]! as String;
              try {
                api.initialize(arg_isolateEpoch);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.create$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final ConfigMsg arg_config = args[0]! as ConfigMsg;
              try {
                final String output = api.create(arg_config);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.start$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_handle = args[0]! as String;
              try {
                await api.start(arg_handle);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.cancel$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_handle = args[0]! as String;
              final String? arg_reason = args[1] as String?;
              try {
                api.cancel(arg_handle, arg_reason);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.perform$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_handle = args[0]! as String;
              final UiActionMsg arg_action = args[1]! as UiActionMsg;
              try {
                api.perform(arg_handle, arg_action);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.dispose$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_handle = args[0]! as String;
              try {
                api.dispose(arg_handle);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.provideAttestation$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final String arg_handle = args[0]! as String;
              final String arg_requestId = args[1]! as String;
              final AttestationTokenMsg? arg_token =
                  args[2] as AttestationTokenMsg?;
              try {
                api.provideAttestation(arg_handle, arg_requestId, arg_token);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
  }
}
