// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum SessionStateMsg {
  idle,
  consent,
  permission,
  connecting,
  active,
  ended,
  error,
}

enum AttestationKindMsg { playIntegrity, appAttest }

enum UiActionMsg { repeat, moreTime, cancel, redial, close }

class IngestCandidateMsg {
  IngestCandidateMsg({required this.region, required this.url});

  String region;

  String url;

  List<Object?> _toList() {
    return <Object?>[region, url];
  }

  Object encode() {
    return _toList();
  }

  static IngestCandidateMsg decode(Object result) {
    result as List<Object?>;
    return IngestCandidateMsg(
      region: result[0]! as String,
      url: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IngestCandidateMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(region, other.region) && _deepEquals(url, other.url);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'IngestCandidateMsg(region: $region, url: $url)';
  }
}

class PromptPackRefMsg {
  PromptPackRefMsg({
    required this.lang,
    required this.version,
    required this.url,
  });

  String lang;

  String version;

  String url;

  List<Object?> _toList() {
    return <Object?>[lang, version, url];
  }

  Object encode() {
    return _toList();
  }

  static PromptPackRefMsg decode(Object result) {
    result as List<Object?>;
    return PromptPackRefMsg(
      lang: result[0]! as String,
      version: result[1]! as String,
      url: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PromptPackRefMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lang, other.lang) &&
        _deepEquals(version, other.version) &&
        _deepEquals(url, other.url);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PromptPackRefMsg(lang: $lang, version: $version, url: $url)';
  }
}

class ThemeMsg {
  ThemeMsg({
    required this.colorTokens,
    this.fontName,
    this.cornerRadius,
    this.logoAssetKey,
  });

  Map<String, String> colorTokens;

  String? fontName;

  double? cornerRadius;

  String? logoAssetKey;

  List<Object?> _toList() {
    return <Object?>[colorTokens, fontName, cornerRadius, logoAssetKey];
  }

  Object encode() {
    return _toList();
  }

  static ThemeMsg decode(Object result) {
    result as List<Object?>;
    return ThemeMsg(
      colorTokens: (result[0]! as Map<Object?, Object?>).cast<String, String>(),
      fontName: result[1] as String?,
      cornerRadius: result[2] as double?,
      logoAssetKey: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThemeMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorTokens, other.colorTokens) &&
        _deepEquals(fontName, other.fontName) &&
        _deepEquals(cornerRadius, other.cornerRadius) &&
        _deepEquals(logoAssetKey, other.logoAssetKey);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ThemeMsg(colorTokens: $colorTokens, fontName: $fontName, cornerRadius: $cornerRadius, logoAssetKey: $logoAssetKey)';
  }
}

class BrandMsg {
  BrandMsg({this.primary, this.logoUrl});

  String? primary;

  String? logoUrl;

  List<Object?> _toList() {
    return <Object?>[primary, logoUrl];
  }

  Object encode() {
    return _toList();
  }

  static BrandMsg decode(Object result) {
    result as List<Object?>;
    return BrandMsg(
      primary: result[0] as String?,
      logoUrl: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BrandMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(primary, other.primary) &&
        _deepEquals(logoUrl, other.logoUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BrandMsg(primary: $primary, logoUrl: $logoUrl)';
  }
}

class UiOptionsMsg {
  UiOptionsMsg({
    required this.character,
    required this.theme,
    this.brand,
    required this.consentCopy,
    required this.alternatePacks,
  });

  bool character;

  ThemeMsg theme;

  BrandMsg? brand;

  Map<String, ConsentCopyMsg> consentCopy;

  List<PromptPackRefMsg> alternatePacks;

  List<Object?> _toList() {
    return <Object?>[character, theme, brand, consentCopy, alternatePacks];
  }

  Object encode() {
    return _toList();
  }

  static UiOptionsMsg decode(Object result) {
    result as List<Object?>;
    return UiOptionsMsg(
      character: result[0]! as bool,
      theme: result[1]! as ThemeMsg,
      brand: result[2] as BrandMsg?,
      consentCopy: (result[3]! as Map<Object?, Object?>)
          .cast<String, ConsentCopyMsg>(),
      alternatePacks: (result[4]! as List<Object?>).cast<PromptPackRefMsg>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UiOptionsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(character, other.character) &&
        _deepEquals(theme, other.theme) &&
        _deepEquals(brand, other.brand) &&
        _deepEquals(consentCopy, other.consentCopy) &&
        _deepEquals(alternatePacks, other.alternatePacks);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UiOptionsMsg(character: $character, theme: $theme, brand: $brand, consentCopy: $consentCopy, alternatePacks: $alternatePacks)';
  }
}

class ConsentCopyMsg {
  ConsentCopyMsg({this.title, this.body, this.recordingNotice});

  String? title;

  String? body;

  String? recordingNotice;

  List<Object?> _toList() {
    return <Object?>[title, body, recordingNotice];
  }

  Object encode() {
    return _toList();
  }

  static ConsentCopyMsg decode(Object result) {
    result as List<Object?>;
    return ConsentCopyMsg(
      title: result[0] as String?,
      body: result[1] as String?,
      recordingNotice: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConsentCopyMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(body, other.body) &&
        _deepEquals(recordingNotice, other.recordingNotice);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConsentCopyMsg(title: $title, body: $body, recordingNotice: $recordingNotice)';
  }
}

class A11yOptionsMsg {
  A11yOptionsMsg({
    this.screenReader,
    this.captions,
    this.reducedMotion,
    this.extendedTime,
  });

  bool? screenReader;

  bool? captions;

  bool? reducedMotion;

  bool? extendedTime;

  List<Object?> _toList() {
    return <Object?>[screenReader, captions, reducedMotion, extendedTime];
  }

  Object encode() {
    return _toList();
  }

  static A11yOptionsMsg decode(Object result) {
    result as List<Object?>;
    return A11yOptionsMsg(
      screenReader: result[0] as bool?,
      captions: result[1] as bool?,
      reducedMotion: result[2] as bool?,
      extendedTime: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! A11yOptionsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(screenReader, other.screenReader) &&
        _deepEquals(captions, other.captions) &&
        _deepEquals(reducedMotion, other.reducedMotion) &&
        _deepEquals(extendedTime, other.extendedTime);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'A11yOptionsMsg(screenReader: $screenReader, captions: $captions, reducedMotion: $reducedMotion, extendedTime: $extendedTime)';
  }
}

class ConfigMsg {
  ConfigMsg({
    required this.clientToken,
    required this.ingest,
    required this.promptPack,
    required this.locale,
    required this.ui,
    required this.accessibility,
    required this.hasAttestationProvider,
    required this.hasTelemetrySink,
    this.priorConsentJson,
    required this.apiBaseUrl,
    required this.defaultTelemetry,
    required this.pinnedIntermediateSpki,
    required this.sessionUiJson,
    required this.wrapperName,
    required this.wrapperVersion,
  });

  String clientToken;

  List<IngestCandidateMsg> ingest;

  PromptPackRefMsg promptPack;

  String locale;

  UiOptionsMsg ui;

  A11yOptionsMsg accessibility;

  bool hasAttestationProvider;

  bool hasTelemetrySink;

  String? priorConsentJson;

  String apiBaseUrl;

  bool defaultTelemetry;

  List<String> pinnedIntermediateSpki;

  String sessionUiJson;

  String wrapperName;

  String wrapperVersion;

  List<Object?> _toList() {
    return <Object?>[
      clientToken,
      ingest,
      promptPack,
      locale,
      ui,
      accessibility,
      hasAttestationProvider,
      hasTelemetrySink,
      priorConsentJson,
      apiBaseUrl,
      defaultTelemetry,
      pinnedIntermediateSpki,
      sessionUiJson,
      wrapperName,
      wrapperVersion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ConfigMsg decode(Object result) {
    result as List<Object?>;
    return ConfigMsg(
      clientToken: result[0]! as String,
      ingest: (result[1]! as List<Object?>).cast<IngestCandidateMsg>(),
      promptPack: result[2]! as PromptPackRefMsg,
      locale: result[3]! as String,
      ui: result[4]! as UiOptionsMsg,
      accessibility: result[5]! as A11yOptionsMsg,
      hasAttestationProvider: result[6]! as bool,
      hasTelemetrySink: result[7]! as bool,
      priorConsentJson: result[8] as String?,
      apiBaseUrl: result[9]! as String,
      defaultTelemetry: result[10]! as bool,
      pinnedIntermediateSpki: (result[11]! as List<Object?>).cast<String>(),
      sessionUiJson: result[12]! as String,
      wrapperName: result[13]! as String,
      wrapperVersion: result[14]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientToken, other.clientToken) &&
        _deepEquals(ingest, other.ingest) &&
        _deepEquals(promptPack, other.promptPack) &&
        _deepEquals(locale, other.locale) &&
        _deepEquals(ui, other.ui) &&
        _deepEquals(accessibility, other.accessibility) &&
        _deepEquals(hasAttestationProvider, other.hasAttestationProvider) &&
        _deepEquals(hasTelemetrySink, other.hasTelemetrySink) &&
        _deepEquals(priorConsentJson, other.priorConsentJson) &&
        _deepEquals(apiBaseUrl, other.apiBaseUrl) &&
        _deepEquals(defaultTelemetry, other.defaultTelemetry) &&
        _deepEquals(pinnedIntermediateSpki, other.pinnedIntermediateSpki) &&
        _deepEquals(sessionUiJson, other.sessionUiJson) &&
        _deepEquals(wrapperName, other.wrapperName) &&
        _deepEquals(wrapperVersion, other.wrapperVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConfigMsg(clientToken: $clientToken, ingest: $ingest, promptPack: $promptPack, locale: $locale, ui: $ui, accessibility: $accessibility, hasAttestationProvider: $hasAttestationProvider, hasTelemetrySink: $hasTelemetrySink, priorConsentJson: $priorConsentJson, apiBaseUrl: $apiBaseUrl, defaultTelemetry: $defaultTelemetry, pinnedIntermediateSpki: $pinnedIntermediateSpki, sessionUiJson: $sessionUiJson, wrapperName: $wrapperName, wrapperVersion: $wrapperVersion)';
  }
}

/// State change plus the session facts of 8.0 item 10.
class StateChangeMsg {
  StateChangeMsg({
    required this.from,
    required this.to,
    this.sessionId,
    this.consentRecord,
  });

  SessionStateMsg from;

  SessionStateMsg to;

  String? sessionId;

  String? consentRecord;

  List<Object?> _toList() {
    return <Object?>[from, to, sessionId, consentRecord];
  }

  Object encode() {
    return _toList();
  }

  static StateChangeMsg decode(Object result) {
    result as List<Object?>;
    return StateChangeMsg(
      from: result[0]! as SessionStateMsg,
      to: result[1]! as SessionStateMsg,
      sessionId: result[2] as String?,
      consentRecord: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StateChangeMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(from, other.from) &&
        _deepEquals(to, other.to) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(consentRecord, other.consentRecord);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StateChangeMsg(from: $from, to: $to, sessionId: $sessionId, consentRecord: $consentRecord)';
  }
}

/// The flat event record of 8.0 item 10.
class EventMsg {
  EventMsg({
    required this.type,
    this.camera,
    this.microphone,
    this.region,
    this.rttMs,
    this.phase,
    this.outcome,
    this.reason,
    this.code,
    this.message,
    this.recoverable,
    this.retryAfterS,
    this.closeCode,
    this.sessionId,
    this.consentRecord,
  });

  String type;

  bool? camera;

  bool? microphone;

  String? region;

  int? rttMs;

  String? phase;

  String? outcome;

  String? reason;

  String? code;

  String? message;

  bool? recoverable;

  int? retryAfterS;

  int? closeCode;

  String? sessionId;

  String? consentRecord;

  List<Object?> _toList() {
    return <Object?>[
      type,
      camera,
      microphone,
      region,
      rttMs,
      phase,
      outcome,
      reason,
      code,
      message,
      recoverable,
      retryAfterS,
      closeCode,
      sessionId,
      consentRecord,
    ];
  }

  Object encode() {
    return _toList();
  }

  static EventMsg decode(Object result) {
    result as List<Object?>;
    return EventMsg(
      type: result[0]! as String,
      camera: result[1] as bool?,
      microphone: result[2] as bool?,
      region: result[3] as String?,
      rttMs: result[4] as int?,
      phase: result[5] as String?,
      outcome: result[6] as String?,
      reason: result[7] as String?,
      code: result[8] as String?,
      message: result[9] as String?,
      recoverable: result[10] as bool?,
      retryAfterS: result[11] as int?,
      closeCode: result[12] as int?,
      sessionId: result[13] as String?,
      consentRecord: result[14] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EventMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(camera, other.camera) &&
        _deepEquals(microphone, other.microphone) &&
        _deepEquals(region, other.region) &&
        _deepEquals(rttMs, other.rttMs) &&
        _deepEquals(phase, other.phase) &&
        _deepEquals(outcome, other.outcome) &&
        _deepEquals(reason, other.reason) &&
        _deepEquals(code, other.code) &&
        _deepEquals(message, other.message) &&
        _deepEquals(recoverable, other.recoverable) &&
        _deepEquals(retryAfterS, other.retryAfterS) &&
        _deepEquals(closeCode, other.closeCode) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(consentRecord, other.consentRecord);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EventMsg(type: $type, camera: $camera, microphone: $microphone, region: $region, rttMs: $rttMs, phase: $phase, outcome: $outcome, reason: $reason, code: $code, message: $message, recoverable: $recoverable, retryAfterS: $retryAfterS, closeCode: $closeCode, sessionId: $sessionId, consentRecord: $consentRecord)';
  }
}

class AttestationRequestMsg {
  AttestationRequestMsg({
    required this.nonce,
    required this.sessionId,
    required this.requestHash,
    required this.requestHashHex,
  });

  Uint8List nonce;

  String sessionId;

  Uint8List requestHash;

  String requestHashHex;

  List<Object?> _toList() {
    return <Object?>[nonce, sessionId, requestHash, requestHashHex];
  }

  Object encode() {
    return _toList();
  }

  static AttestationRequestMsg decode(Object result) {
    result as List<Object?>;
    return AttestationRequestMsg(
      nonce: result[0]! as Uint8List,
      sessionId: result[1]! as String,
      requestHash: result[2]! as Uint8List,
      requestHashHex: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttestationRequestMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(nonce, other.nonce) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(requestHash, other.requestHash) &&
        _deepEquals(requestHashHex, other.requestHashHex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AttestationRequestMsg(nonce: $nonce, sessionId: $sessionId, requestHash: $requestHash, requestHashHex: $requestHashHex)';
  }
}

class AttestationTokenMsg {
  AttestationTokenMsg({
    required this.kind,
    this.token,
    this.appAttestKeyId,
    this.appAttestAttestation,
    this.appAttestAssertion,
  });

  AttestationKindMsg kind;

  String? token;

  String? appAttestKeyId;

  Uint8List? appAttestAttestation;

  Uint8List? appAttestAssertion;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      token,
      appAttestKeyId,
      appAttestAttestation,
      appAttestAssertion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AttestationTokenMsg decode(Object result) {
    result as List<Object?>;
    return AttestationTokenMsg(
      kind: result[0]! as AttestationKindMsg,
      token: result[1] as String?,
      appAttestKeyId: result[2] as String?,
      appAttestAttestation: result[3] as Uint8List?,
      appAttestAssertion: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttestationTokenMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(token, other.token) &&
        _deepEquals(appAttestKeyId, other.appAttestKeyId) &&
        _deepEquals(appAttestAttestation, other.appAttestAttestation) &&
        _deepEquals(appAttestAssertion, other.appAttestAssertion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AttestationTokenMsg(kind: $kind, token: $token, appAttestKeyId: $appAttestKeyId, appAttestAttestation: $appAttestAttestation, appAttestAssertion: $appAttestAssertion)';
  }
}

class TelemetryMsg {
  TelemetryMsg({
    required this.name,
    this.sessionId,
    required this.tMs,
    required this.fields,
  });

  String name;

  String? sessionId;

  int tMs;

  Map<String, Object?> fields;

  List<Object?> _toList() {
    return <Object?>[name, sessionId, tMs, fields];
  }

  Object encode() {
    return _toList();
  }

  static TelemetryMsg decode(Object result) {
    result as List<Object?>;
    return TelemetryMsg(
      name: result[0]! as String,
      sessionId: result[1] as String?,
      tMs: result[2]! as int,
      fields: (result[3]! as Map<Object?, Object?>).cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TelemetryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(tMs, other.tMs) &&
        _deepEquals(fields, other.fields);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TelemetryMsg(name: $name, sessionId: $sessionId, tMs: $tMs, fields: $fields)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SessionStateMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AttestationKindMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is UiActionMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is IngestCandidateMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PromptPackRefMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ThemeMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is BrandMsg) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is UiOptionsMsg) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ConsentCopyMsg) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is A11yOptionsMsg) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is ConfigMsg) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is StateChangeMsg) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is EventMsg) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is AttestationRequestMsg) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is AttestationTokenMsg) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is TelemetryMsg) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SessionStateMsg.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AttestationKindMsg.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : UiActionMsg.values[value];
      case 132:
        return IngestCandidateMsg.decode(readValue(buffer)!);
      case 133:
        return PromptPackRefMsg.decode(readValue(buffer)!);
      case 134:
        return ThemeMsg.decode(readValue(buffer)!);
      case 135:
        return BrandMsg.decode(readValue(buffer)!);
      case 136:
        return UiOptionsMsg.decode(readValue(buffer)!);
      case 137:
        return ConsentCopyMsg.decode(readValue(buffer)!);
      case 138:
        return A11yOptionsMsg.decode(readValue(buffer)!);
      case 139:
        return ConfigMsg.decode(readValue(buffer)!);
      case 140:
        return StateChangeMsg.decode(readValue(buffer)!);
      case 141:
        return EventMsg.decode(readValue(buffer)!);
      case 142:
        return AttestationRequestMsg.decode(readValue(buffer)!);
      case 143:
        return AttestationTokenMsg.decode(readValue(buffer)!);
      case 144:
        return TelemetryMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ZakadiHostApi {
  /// Constructor for [ZakadiHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ZakadiHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Closes sessions created by an earlier Dart isolate (hot restart); records this isolate's epoch.
  Future<void> initialize(String isolateEpoch) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[isolateEpoch],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Constructs the native ZakadiSession; returns its handle. Errors: unsupported_device, usage_error.
  Future<String> create(ConfigMsg config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Completes at `active`; otherwise throws ZakadiPigeonError(code = 5.11 wire code).
  Future<void> start(String handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(String handle, String? reason) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, reason],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> perform(String handle, UiActionMsg action) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.perform$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, action],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> dispose(String handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Reply to ZakadiFlutterApi.onAttestationRequested; null = no attestation.
  Future<void> provideAttestation(
    String handle,
    String requestId,
    AttestationTokenMsg? token,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiHostApi.provideAttestation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, requestId, token],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class ZakadiFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onState(String handle, StateChangeMsg change);

  void onEvent(String handle, EventMsg event);

  void onAttestationRequested(
    String handle,
    String requestId,
    AttestationRequestMsg request,
  );

  void onTelemetry(String handle, TelemetryMsg event);

  static void setUp(
    ZakadiFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onState$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_handle = args[0]! as String;
          final StateChangeMsg arg_change = args[1]! as StateChangeMsg;
          try {
            api.onState(arg_handle, arg_change);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_handle = args[0]! as String;
          final EventMsg arg_event = args[1]! as EventMsg;
          try {
            api.onEvent(arg_handle, arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onAttestationRequested$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_handle = args[0]! as String;
          final String arg_requestId = args[1]! as String;
          final AttestationRequestMsg arg_request =
              args[2]! as AttestationRequestMsg;
          try {
            api.onAttestationRequested(arg_handle, arg_requestId, arg_request);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.zakadi_sdk_android.ZakadiFlutterApi.onTelemetry$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_handle = args[0]! as String;
          final TelemetryMsg arg_event = args[1]! as TelemetryMsg;
          try {
            api.onTelemetry(arg_handle, arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
